# Generated by Django 5.2 on 2025-04-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Slot', max_length=50)),
                ('slot_name', models.CharField(default='Unnamed Slot', max_length=100)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_slots', to='EldenRingInsider.build')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erdb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('talisman', 'Talisman'), ('spell', 'Spell'), ('ash_of_war', 'Ash of War'), ('consumable', 'Consumable'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('required_stats', models.JSONField(blank=True, null=True)),
                ('attack_power', models.JSONField(blank=True, null=True)),
                ('defense', models.JSONField(blank=True, null=True)),
                ('spell_requirements', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='EldenRingIn_type_3c3631_idx'), models.Index(fields=['name'], name='EldenRingIn_name_678005_idx')],
            },
        ),
        migrations.AddField(
            model_name='build',
            name='items',
            field=models.ManyToManyField(blank=True, to='EldenRingInsider.item'),
        ),
    ]
