# Generated by Django 5.1.4 on 2025-01-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=200),
        ),
    ]
