# Generated by Django 5.2 on 2025-04-29 09:22

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentslot',
            unique_together={('build', 'name')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attack_power'], name='EldenRingIn_attack__8ff44f_gin'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['defense'], name='EldenRingIn_defense_2a6e22_gin'),
        ),
    ]
