# Generated by Django 5.2 on 2025-04-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0002_alter_equipmentslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='scaling',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
