# Generated by Django 5.1.4 on 2025-01-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0002_alter_item_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(default='/static/placeholder.jpg', max_length=255),
        ),
    ]
