# Generated by Django 5.2 on 2025-04-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0003_item_scaling'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='EldenRingIn_type_3c3631_idx',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='item_type',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_type'], name='EldenRingIn_item_ty_5c414f_idx'),
        ),
    ]
