# Generated by Django 5.1.4 on 2025-01-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0003_remove_item_item_type_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
