# Generated by Django 5.2 on 2025-04-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0004_remove_item_eldenringin_type_3c3631_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='EldenRingIn_item_ty_5c414f_idx',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='type',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['type'], name='EldenRingIn_type_3c3631_idx'),
        ),
    ]
