# Generated by Django 5.1.4 on 2025-04-22 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0005_alter_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(choices=[('RH1', 'Right Hand 1'), ('LH1', 'Left Hand 1'), ('Helmet', 'Helmet'), ('Armor', 'Armor'), ('Gauntlets', 'Gauntlets'), ('Boots', 'Boots'), ('Talisman1', 'Talisman Slot 1'), ('Talisman2', 'Talisman Slot 2'), ('Talisman3', 'Talisman Slot 3'), ('Talisman4', 'Talisman Slot 4'), ('Flask1', 'Flask Slot 1'), ('Flask2', 'Flask Slot 2'), ('Flask3', 'Flask Slot 3')], max_length=20)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_slots', to='EldenRingInsider.build')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EldenRingInsider.item')),
            ],
        ),
    ]
