# Generated by Django 5.2 on 2025-05-13 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0005_remove_item_eldenringin_item_ty_5c414f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='items',
        ),
        migrations.AlterUniqueTogether(
            name='equipmentslot',
            unique_together={('build', 'slot_name')},
        ),
        migrations.AddField(
            model_name='equipmentslot',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EldenRingInsider.item'),
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='slot_name',
            field=models.CharField(choices=[('RH1', 'Right Hand 1'), ('RH2', 'Right Hand 2'), ('LH1', 'Left Hand 1'), ('LH2', 'Left Hand 2'), ('Helmet', 'Helmet'), ('Armor', 'Armor'), ('Gauntlets', 'Gauntlets'), ('Boots', 'Boots'), ('Talisman1', 'Talisman Slot 1'), ('Talisman2', 'Talisman Slot 2'), ('Talisman3', 'Talisman Slot 3'), ('Talisman4', 'Talisman Slot 4'), ('Spell1', 'Spell Slot 1'), ('Spell2', 'Spell Slot 2'), ('Spell3', 'Spell Slot 3'), ('Spell4', 'Spell Slot 4'), ('AshOfWar1', 'Ash of War 1'), ('AshOfWar2', 'Ash of War 2')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='equipmentslot',
            name='name',
        ),
    ]
