# Generated by Django 5.2 on 2025-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0006_remove_build_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentslot',
            name='slot_name',
            field=models.CharField(choices=[('RH1', 'Right Hand 1'), ('RH2', 'Right Hand 2'), ('LH1', 'Left Hand 1'), ('LH2', 'Left Hand 2'), ('Helms', 'Helms'), ('Chest Armor', 'Chest Armor'), ('Gauntlets', 'Gauntlets'), ('Greaves', 'Greaves'), ('Talisman1', 'Talisman Slot 1'), ('Talisman2', 'Talisman Slot 2'), ('Talisman3', 'Talisman Slot 3'), ('Talisman4', 'Talisman Slot 4'), ('Spell1', 'Spell Slot 1'), ('Spell2', 'Spell Slot 2'), ('Spell3', 'Spell Slot 3'), ('Spell4', 'Spell Slot 4'), ('AshOfWar1', 'Ash of War 1'), ('AshOfWar2', 'Ash of War 2')], max_length=50),
        ),
    ]
