# Generated by Django 5.2 on 2025-05-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0007_alter_equipmentslot_slot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
