# Generated by Django 5.2 on 2025-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0008_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
