# Generated by Django 5.2 on 2025-06-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0011_item_effect_item_role_alter_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='effect',
            new_name='effects',
        ),
    ]
