# Generated by Django 5.2 on 2025-06-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0013_remove_item_spell_requirements_item_fp_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('small_shield', 'Small Shield'), ('medium_shield', 'Medium Shield'), ('greatshield', 'Greatshield'), ('staff', 'Staff'), ('glintstone_staff', 'Glintstone Staff'), ('sacred_seal', 'Sacred Seal'), ('ballista', 'Ballista'), ('crossbow', 'Crossbow'), ('bow', 'Bow'), ('light_bow', 'Light Bow'), ('greatbow', 'Greatbow'), ('katana', 'Katana'), ('great_katana', 'Great Katana'), ('greatsword', 'Greatsword'), ('colossal_sword', 'Colossal Sword'), ('colossal_weapon', 'Colossal Weapon'), ('curved_sword', 'Curved Sword'), ('straightsword', 'Straight Sword'), ('dagger', 'Dagger'), ('twinblade', 'Twinblade'), ('axe', 'Axe'), ('great_axe', 'Great Axe'), ('hammer', 'Hammer'), ('great_hammer', 'Great Hammer'), ('flail', 'Flail'), ('spear', 'Spear'), ('short_spear', 'Short Spear'), ('great_spear', 'Great Spear'), ('halberd', 'Halberd'), ('heavy_thrusting_sword', 'Heavy Thrusting Sword'), ('thrusting_sword', 'Thrusting Sword'), ('claw', 'Claw'), ('fists', 'Fists'), ('backhand_blade', 'Backhand Blade'), ('reaper', 'Reaper'), ('whip', 'Whip'), ('torch', 'Torch'), ('head', 'Head'), ('body', 'Body'), ('arms', 'Arms'), ('legs', 'Legs'), ('talisman', 'Talisman'), ('spell', 'Spell'), ('ash_of_war', 'Ash of War'), ('consumable', 'Consumable'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
