# Generated by Django 5.2.6 on 2025-09-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0014_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
