# Generated by Django 5.2.6 on 2025-09-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldenRingInsider', '0015_alter_build_name_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
